i18n:
  all-locale: zh,en
  language: zh
  path: i18n/messages
server:
  port: 8001
doc:
  title: 机器人发送消息测试用例
  enabled: true
  globalRequestParameters:
    - name: token
      in: HEADER
      description: 用户认证令牌
      required: true
      deprecated: false
      hidden: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jmx:
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
bot:
  note:
    ding-talk:
      secret:
      url:
    wechat:
      url: