i18n:
  all-locale: zh,en
  language: zh
  path: i18n/messages
server:
  port: 8001
doc:
  title: xxlJob测试用例
  enabled: true
  globalRequestParameters:
    - name: token
      in: HEADER
      description: 用户认证令牌
      required: true
      deprecated: false
      hidden: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jmx:
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: 123456
xxl:
  access-token: default_token
  app-name: xxl-job-executor-sample
  admin-addresses: http://localhost:8080/xxl-job-admin
  user-name: admin
  password: 123456
  log-path: 日志路径

