version: '3'

services:
  h2:
    image: oscarfonts/h2
    container_name: h2_database
    ports:
      - "81:81"  # 显式绑定 Web 控制台端口
      - "1521:1521"  # TCP 端口
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -web -webAllowOthers -ifNotExists
    volumes:
      - ./data:/opt/h2-data
    restart: always
