i18n:
  all-locale: zh,en
  language: zh
  path: i18n/messages
server:
  port: 8001
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        packages-to-scan: com.steven
  # knife4j的增强配置，不需要增强可以不配
  knife4j:
    enable: true
    setting:
      language: zh_cn
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jmx:
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
file:
  bucket-name: default
  choice: DEFAULT
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: admin12345678
  file-naming-method: date
clamav:
  enabled: true
  host: 127.0.0.1
  port: 3310
  platform: unix